### PR TITLE
bump version to 3.0.1

### PR DESCRIPTION
**Pull request by timgraham**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/django-cockroachdb/143)

### CODE REVIEW

**Comment by timgraham** [comment]
(test failure is https://github.com/cockroachdb/django-cockroachdb/issues/141, will retry later)

**Comment by timgraham** [comment]
Build passes now. Need an approval to merge.

**Comment by timgraham** [comment]
I'm not familiar with Reviewable.

**Comment by rafiss** [comment]
Huh, strange. somehow this message showed up in the PR

image

**Pull request merged**
