### PR TITLE
additional info in readme

### PR DESCRIPTION
**Pull request by dbist**

### CODE REVIEW

**Comment by timgraham** [comment]
I think the current instructions should be sufficient. Did you find them unclear?

The new instructions aren't correct because `django-cockroachdb>=2.2a1` will install the latest version without an upper bound (3.0a1 as of now).

Perhaps the situation will be less confusing once we make a non-pre-release.

**Comment by dbist** [comment]
I updated based on your comments, I do feel the instructions only reflect 3.x version and no clear mention that there is a 2.x version available. @timgraham. Happy to help whichever way.

**Comment by timgraham** [comment]
That's sort of intentional. The master branch (and this version of the README) is targeted at Django 3.0.x. There's a separate branch for Django 2.2.x support: https://github.com/cockroachdb/django-cockroachdb/tree/stable/2.2.x.

**Comment by dbist** [comment]
duh, ok, let's ignore this then. Thanks for being patient with me.

**Pull request closed without merging**
