### PR TITLE
fix dbshell if connecting with SSL

### PR DESCRIPTION
**Pull request by timgraham**

### CODE REVIEW

**Comment by timgraham** [comment]
@dbist could you please verify that this patch fixes `python manage.py dbshell` on your SSL setup?

**Comment by dbist** [comment]
@timgraham please provide steps to get a binary `django-cockroach` with this patch so I could test it? This is what I got on my setup so far:

```
root@cf18d5f75ce1:/code# python manage.py dbshell
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
Error: SSL authentication error while connecting.

If the node is configured to require secure connections,
remove --insecure and configure secure credentials instead.

pq: node is running secure mode, SSL connection required
Failed running "sql"
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/dbshell.py", line 22, in handle
    connection.client.runshell()
  File "/usr/local/lib/python3.7/site-packages/django_cockroachdb/client.py", line 45, in runshell
    subprocess.check_call(args)
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cockroach', 'sql', '--database=myproject', '--user=myprojectuser', '--host=roach-0', '--port=26257', '--insecure']' returned non-zero exit status 1.
```

why does it think I'm using `--insecure`?

my pip list is as so:

```
root@cf18d5f75ce1:/code# pip list
Package            Version
------------------ -------
asgiref            3.2.3
cockroachdb        0.3.3
Django             3.0.1
django-cockroachdb 3.0a1
pip                19.3.1
psycopg2           2.8.4
pytz               2019.3
setuptools         41.6.0
sqlparse           0.3.0
wheel              0.33.6
```

**Comment by timgraham** [comment]
You've demonstrated the bug this is intended to fix. You can download this patch (https://github.com/cockroachdb/django-cockroachdb/pull/111.diff) and apply it or manually edit the source file that you installed (/usr/local/lib/python3.7/site-packages/django_cockroachdb/client.py) to test the fix.

**Comment by dbist** [comment]
@timgraham patch works,

```
root@20d2917e0e3a:/code# python manage.py dbshell
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
# Client version: CockroachDB CCL v19.2.2 (x86_64-unknown-linux-gnu, built 2019/12/11 01:33:43, go1.12.12)
# Server version: CockroachDB CCL v19.2.1 (x86_64-unknown-linux-gnu, built 2019/11/18 23:23:55, go1.12.12)

warning: server version older than client! proceed with caution; some features may not be available.

# Cluster ID: dc239986-f1c3-45bd-9bea-62a58ac8de60
#
# Enter \? for a brief introduction.
#
```

**Pull request merged**
