### PR TITLE
ci: add placeholder script for CockroachDB 22.2 and nightly builds

### PR DESCRIPTION
**Pull request by timgraham**
Also remove CockroachDB 20.1 script.

### CODE REVIEW

**Comment by timgraham** [comment]
@rafiss could you please make these additions and removal in TeamCity?

**Review by rafiss — APPROVED** [review]
lgtm! if you'd like to, we could start using the 22.2 beta here

**Comment by timgraham** [comment]
Thanks. Did you add build-teamcity-nightly.sh? I don't see it at https://teamcity.cockroachdb.com/viewLog.html?buildId=6892790&buildTypeId=Cockroach_CockroachDjango. 22.2 is forthcoming in https://github.com/cockroachdb/django-cockroachdb/pull/261.

**Comment by rafiss** [comment]
I missed that earlier. added now

**Pull request merged**
